#!/bin/sh /etc/rc.common
START=90

run_udpgame()
{
	local server
	local service_port
	local udp2raw_port
	local password
	local fec
	local mode
	
	config_get server $1 server
	config_get service_port $1 service_port
	config_get udp2raw_port $1 udp2raw_port
	config_get password $1 password
	config_get fec $1 fec
	config_get mode $1 mode

	(tinymapper -l 0.0.0.0:$service_port -r 10.22.22.1:$service_port -t -u >/dev/null 2>&1 )&
	(tinyfecvpn -c -r 127.0.0.1:24444 --sub-net 10.22.22.0 -f $fec --tun-dev tun100 --mode $mode -k $password --keep-reconnect >/dev/null 2>&1 )&
	(udp2raw -c -l 127.0.0.1:24444 -r $server:$udp2raw_port --raw-mode faketcp -a -k $password >/dev/null 2>&1 )&
}

start()
{
	config_load udpgame
	config_foreach run_udpgame udpgame    
}

stop()
{
	killall -9 tinymapper
	killall -9 tinyfecvpn
	killall -9 udp2raw
}